name: warehouse_master_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  dio: ^5.7.0
  intl: ^0.18.0
  qr_code_dart_scan: ^0.9.3
  qr_code_scanner: ^1.0.1
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
