name: warehouse_master_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  dio: ^5.7.0
  intl: ^0.18.0
  shimmer: ^2.0.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  qr_code_dart_scan: ^0.9.3
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"